---
include:
  - board: xiao_ble//zmk
    shield: totem_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: totem-left

  - board: xiao_ble//zmk
    shield: totem_right
    artifact-name: totem-right

  - board: cornix_left
    artifact-name: cornix-left

  - board: cornix_right
    artifact-name: cornix-right

  - board: cornix_right
    shield: settings_reset
    artifact-name: cornix-settings-reset
