parse_config:
  trans_legend: {t: "", type: trans}
  modifier_fn_map:
    left_gui: "LCMD"
    right_gui: "RCMD"
  raw_binding_map:
    "&mmv MOVE_UP": "Move ↑"
    "&mmv MOVE_DOWN": "Move ↓"
    "&mmv MOVE_LEFT": "Move ←"
    "&mmv MOVE_RIGHT": "Move →"
    "&msc SCRL_UP": "Scroll ↑"
    "&msc SCRL_DOWN": "Scroll ↓"
    "&msc SCRL_LEFT": "Scroll ←"
    "&msc SCRL_RIGHT": "Scroll →"
    "&mkp LCLK": "Left Click"
    "&mkp RCLK": "Right Click"
    "&mkp MCLK": "Middle Click"
    "&bootloader": "Boot"

    "&kp LC(LS(LA(LGUI)))": "Hyper"
    "&kp LC(LA(LGUI))": "Super"
    "&kp LG(LS(Z))": "Redo"
    "&kp LG(C)": "Copy"
    "&kp LG(Z)": "Undo"
    "&kp LS(TAB)": "Prev Tab"
    "&kp LG(V)": "Paste"

draw_config:
  key_w: 64
  key_h: 56
  inner_pad_w: 2
  outer_pad_w: 2
  outer_pad_h: 64
  line_spacing: 1.05
  key_rx: 5
  key_ry: 5
  dark_mode: false
  append_colon_to_layer_header: false
