name: Build ZMK firmware

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ".github/workflows/build.yml"
      - "build.yaml"
      - "config/**"
      - "boards/**"
      - "zephyr/**"
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - "build.yaml"
      - "config/**"
      - "boards/**"
      - "zephyr/**"

permissions:
  contents: read

concurrency:
  group: zmk-build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@904c9aec8822d79149d42c8a9a77e8828eb08f5a
