name: Draw keymap

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "config/totem.keymap"
      - "boards/shields/totem/**"
      - "keymap_drawer.config.yaml"
      - ".github/workflows/draw-keymap.yml"

concurrency:
  group: keymap-drawer-${{ github.ref }}
  cancel-in-progress: true

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@a44809b8cc718cbff646641f49a8f71a9368336d
    permissions:
      contents: write
    with:
      keymap_patterns: "config/totem.keymap"
      config_path: "keymap_drawer.config.yaml"
      west_config_path: ""
      output_folder: "keymap-drawer"
      parse_args: "totem:'-c 10'"
      draw_args: "totem:'-s BASE VI FN NUM MOUSE'"
      install_version: "0.23.0"
      fail_on_error: true
